version: '{build}'

pull_requests:
  do_not_increment_build_number: true

branches:
  only:
  - master

nuget:
  disable_publish_on_pr: true

init:
- git config --global core.autocrlf true

build_script:
- ps: .\build.ps1

test: off

cache:
- tools -> build.cake
- tools -> build.ps1

artifacts:
- path: nupkgs\*.nupkg
  name: NuPkgs

deploy:
- provider: Environment
  name: nuget.org
  on:
    branch: master