version: '{build}'
image: Visual Studio 2017

pull_requests:
  do_not_increment_build_number: true

branches:
  only:
  - master

nuget:
  disable_publish_on_pr: true

before_build:
  - cmd: dotnet restore

after_build:
- dotnet pack "src\Narochno.Credstash" -c Release
- dotnet pack "src\Narochno.Credstash.Configuration" -c Release

artifacts:
- path: src\Narochno.Credstash\bin\Release\*.nupkg
- path: src\Narochno.Credstash.Configuration\bin\Release\*.nupkg

deploy:
- provider: Environment
  name: nuget.org
  on:
    branch: master
    